#!/bin/sh
echo
echo 'START---------------'
echo 'current dir: ' ${PWD}
cd /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis
echo 'current dir: ' ${PWD}
source scripts/setup.sh
parallel --results ./jobs/myTask_step2/ /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/bin/moduleCharacterization_step2.exe ::: /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2375.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2376.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2377.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2378.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2379.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2380.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2381.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2382.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2383.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2384.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2385.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2386.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2387.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2388.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2389.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2390.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2391.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2392.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2393.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2394.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2395.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2396.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2397.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2398.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2399.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2400.cfg /home/cmsdaq/alio_guglielmi_corr/Lab5015Analysis/jobs/myTask_step2//config_run2401.cfg 
echo 'STOP---------------'
echo
echo
