executable            = moduleCharacterizationCondor.sh
arguments             = $(cfg)
output                = /afs/cern.ch/work/m/malberti/MTD/TBatH8May2023/Lab5015Analysis/scripts/jobs/job_moduleCharact.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/m/malberti/MTD/TBatH8May2023/Lab5015Analysis/scripts/jobs/job_moduleCharact.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/m/malberti/MTD/TBatH8May2023/Lab5015Analysis/scripts/jobs/job_moduleCharact.$(ClusterId).$(ProcId).log
+JobFlavour = "longlunch"
queue cfg from list_cfg_moduleCharacterization.txt