executable            = moduleCharacterizationCondor.sh
arguments             = $(cfg)
output                = /afs/cern.ch/user/f/ftonetto/francesco/Lab5015Analysis/scripts/jobs/job_moduleCharact.out
error                 = /afs/cern.ch/user/f/ftonetto/francesco/Lab5015Analysis/scripts/jobs/job_moduleCharact.err
log                   = /afs/cern.ch/user/f/ftonetto/francesco/Lab5015Analysis/scripts/jobs/job_moduleCharact.log
+JobFlavour = "longlunch"
queue cfg from list_cfg_moduleCharacterization.txt
