executable            = moduleCharacterizationCondor.sh
arguments             = $(cfg)
output                = /eos/home-f/ftonetto/Lab5015Analysis/scripts/jobs/job_moduleCharact.out
error                 = /eos/home-f/ftonetto/Lab5015Analysis/scripts/jobs/job_moduleCharact.err
log                   = /eos/home-f/ftonetto/Lab5015Analysis/scripts/jobs/job_moduleCharact.log
+JobFlavour = "workday"
queue cfg from list_cfg_moduleCharacterization.txt

#output                = /eos/home-f/ftonetto/Lab5015Analysis/scripts/jobs/job_moduleCharact.$(ClusterId).$(ProcId).out